#!/usr/bin/env bash
# Deploy path2v2x/v2x-digital-twin to path-rfs.
#
#   scripts/deploy.sh                twin server (+ units, nginx vhost)
#   scripts/deploy.sh --perception   also restart v2x-perception (co-perception)
#   scripts/deploy.sh --studio       also pull, build and restart the Studio UI
#   scripts/deploy.sh --dry-run      print the plan without touching the host
#
# The checkout on the host is fast-forwarded to origin/main, so push first.
# The Studio UI is a separate SimForgeinc/simforge-oss checkout on the host
# (main); --studio fast-forwards it and rebuilds with the production env file
# because NEXT_PUBLIC_* values are inlined at build time.
set -euo pipefail

HOST="${DEPLOY_HOST:-root@100.126.56.83}"
APP_USER=path
CHECKOUT=/home/path/v2x-digital-twin
STUDIO_CHECKOUT=/home/path/simforge-oss
STUDIO_ENV=/etc/v2x-twin-studio.env
PUBLIC_URL="${DEPLOY_PUBLIC_URL:-https://twin.path2v2x.net}"

restart_perception=0
deploy_studio=0
dry_run=0
for arg in "$@"; do
  case "$arg" in
    --perception) restart_perception=1 ;;
    --studio) deploy_studio=1 ;;
    --dry-run) dry_run=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 64 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ -n "$(git -C "$REPO_ROOT" status --porcelain)" ]; then
  echo "warning: local working tree has uncommitted changes; the host deploys origin/main" >&2
fi

step() { printf '\n== %s\n' "$1"; }
remote() { ssh -o BatchMode=yes "$HOST" "$@"; }
remote_as_app() { remote su - "$APP_USER" -c "\"$*\""; }
check_http() {
  local url="$1" expect="${2:-200}"
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$url")"
  [ "$code" = "$expect" ] || { echo "  $url returned $code (expected $expect)" >&2; exit 1; }
  echo "  $url $code"
}

plan=(
  "fast-forward $CHECKOUT to origin/main as $APP_USER"
  "pnpm install --frozen-lockfile when pnpm-lock.yaml changed"
  "install scripts/systemd/*.service, deploy/nginx-twin.conf; daemon-reload; nginx -t + reload"
  "restart v2x-twin-server; health: 127.0.0.1:8190/health all feeds live, $PUBLIC_URL/detections/coverage 200"
)
[ "$restart_perception" = 1 ] && plan+=("restart v2x-perception; health: 127.0.0.1:8091/health")
[ "$deploy_studio" = 1 ] && plan+=("fast-forward $STUDIO_CHECKOUT (main), pnpm install --frozen-lockfile, build packages + Studio with $STUDIO_ENV, restart v2x-twin-studio; health: $PUBLIC_URL/dashboard/drive 200")
step "Plan ($HOST)"
printf '  - %s\n' "${plan[@]}"
[ "$dry_run" = 1 ] && exit 0

step "Fast-forward checkout"
before="$(remote_as_app git -C "$CHECKOUT" rev-parse HEAD)"
remote_as_app git -C "$CHECKOUT" pull -q --ff-only origin main
after="$(remote_as_app git -C "$CHECKOUT" rev-parse HEAD)"
echo "  $before -> $after"
if [ "$before" = "$after" ] || remote_as_app git -C "$CHECKOUT" diff --quiet "$before" "$after" -- pnpm-lock.yaml; then
  echo "  lockfile unchanged; skipping pnpm install"
else
  remote_as_app "cd $CHECKOUT && pnpm install --frozen-lockfile --silent"
fi

step "Units and nginx"
remote "install -m 644 $CHECKOUT/scripts/systemd/v2x-twin-server.service $CHECKOUT/scripts/systemd/v2x-perception.service $CHECKOUT/deploy/v2x-twin-studio.service /etc/systemd/system/ && systemctl daemon-reload"
remote "install -m 644 $CHECKOUT/deploy/nginx-twin.conf /etc/nginx/sites-available/v2x-twin && nginx -t && systemctl reload nginx"

step "Twin server"
remote "systemctl restart v2x-twin-server"
for _ in $(seq 1 20); do
  health="$(remote 'curl -s --max-time 2 127.0.0.1:8190/health' || true)"
  case "$health" in *'"status":"ok"'*) break ;; esac
  sleep 2
done
case "$health" in *'"status":"ok"'*) echo "  $health" ;; *) echo "  twin server unhealthy: $health" >&2; exit 1 ;; esac
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
earlier="$(date -u -d '-10 minutes' +%Y-%m-%dT%H:%M:%SZ)"
check_http "$PUBLIC_URL/detections/coverage?start=$earlier&end=$now&bucket=300"

if [ "$restart_perception" = 1 ]; then
  step "Perception"
  remote "systemctl restart v2x-perception"
  for _ in $(seq 1 60); do
    phealth="$(remote 'curl -s --max-time 2 127.0.0.1:8091/health' || true)"
    case "$phealth" in *'"ok"'*|*'"status":"ok"'*) break ;; esac
    sleep 3
  done
  case "$phealth" in *ok*) echo "  $phealth" ;; *) echo "  perception unhealthy: $phealth" >&2; exit 1 ;; esac
fi

if [ "$deploy_studio" = 1 ]; then
  step "Studio UI"
  sbefore="$(remote_as_app git -C "$STUDIO_CHECKOUT" rev-parse HEAD)"
  # studio/next-env.d.ts is regenerated by Next on every boot; keep it out of the way.
  remote_as_app "git -C $STUDIO_CHECKOUT checkout -- studio/next-env.d.ts 2>/dev/null; git -C $STUDIO_CHECKOUT pull -q --ff-only origin main"
  safter="$(remote_as_app git -C "$STUDIO_CHECKOUT" rev-parse HEAD)"
  echo "  $sbefore -> $safter"
  if [ "$sbefore" = "$safter" ] || remote_as_app git -C "$STUDIO_CHECKOUT" diff --quiet "$sbefore" "$safter" -- pnpm-lock.yaml; then
    echo "  lockfile unchanged; skipping pnpm install"
  else
    remote_as_app "cd $STUDIO_CHECKOUT && pnpm install --frozen-lockfile --silent"
  fi
  # Workspace packages export built dist/ files under the production condition.
  remote_as_app "cd $STUDIO_CHECKOUT && pnpm -r --filter './packages/**' build >/tmp/simforge-packages-build.log 2>&1 || (tail -40 /tmp/simforge-packages-build.log; exit 1)"
  remote_as_app "cd $STUDIO_CHECKOUT && set -a && . $STUDIO_ENV && set +a && pnpm --filter @simforge-oss/studio build"
  remote "systemctl restart v2x-twin-studio"
  for _ in $(seq 1 60); do
    code="$(remote 'curl -s -o /dev/null -w %{http_code} --max-time 5 http://127.0.0.1:5199/dashboard/drive' || true)"
    [ "$code" = 200 ] && break
    sleep 2
  done
  [ "$code" = 200 ] || { echo "  studio returned $code" >&2; exit 1; }
  check_http "$PUBLIC_URL/dashboard/drive"
fi

echo "deployed $after"
